//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.System {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="System.ISystem")]
    public interface ISystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/AddSystemCountryCodeResponse")]
        void AddSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/AddSystemCountryCodeResponse")]
        System.Threading.Tasks.Task AddSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemCountryCodeResponse")]
        CareerCloud.Pocos.SystemCountryCodePoco[] GetAllSystemCountryCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemCountryCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco[]> GetAllSystemCountryCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemCountryCodeResponse")]
        CareerCloud.Pocos.SystemCountryCodePoco GetSingleSystemCountryCode(System.Guid Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemCountryCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco> GetSingleSystemCountryCodeAsync(System.Guid Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemCountryCodeResponse")]
        void RemoveSystemCountryCode(System.Guid Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemCountryCodeResponse")]
        System.Threading.Tasks.Task RemoveSystemCountryCodeAsync(System.Guid Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemCountryCodeResponse")]
        void UpdateSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemCountryCodeResponse")]
        System.Threading.Tasks.Task UpdateSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/AddSystemLanguageCodeResponse")]
        void AddSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/AddSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task AddSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemLanguageCodeResponse")]
        CareerCloud.Pocos.SystemLanguageCodePoco[] GetAllSystemLanguageCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco[]> GetAllSystemLanguageCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeResponse")]
        CareerCloud.Pocos.SystemLanguageCodePoco GetSingleSystemLanguageCode(System.Guid LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco> GetSingleSystemLanguageCodeAsync(System.Guid LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemLanguageCodeResponse")]
        void RemoveSystemLanguageCode(System.Guid LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task RemoveSystemLanguageCodeAsync(System.Guid LanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemLanguageCodeResponse")]
        void UpdateSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task UpdateSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemChannel : CareerCloud.UnitTests.Assignment5.System.ISystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.System.ISystem>, CareerCloud.UnitTests.Assignment5.System.ISystem {
        
        public SystemClient() {
        }
        
        public SystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            base.Channel.AddSystemCountryCode(item);
        }
        
        public System.Threading.Tasks.Task AddSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] item) {
            return base.Channel.AddSystemCountryCodeAsync(item);
        }
        
        public CareerCloud.Pocos.SystemCountryCodePoco[] GetAllSystemCountryCode() {
            return base.Channel.GetAllSystemCountryCode();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco[]> GetAllSystemCountryCodeAsync() {
            return base.Channel.GetAllSystemCountryCodeAsync();
        }
        
        public CareerCloud.Pocos.SystemCountryCodePoco GetSingleSystemCountryCode(System.Guid Code) {
            return base.Channel.GetSingleSystemCountryCode(Code);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco> GetSingleSystemCountryCodeAsync(System.Guid Code) {
            return base.Channel.GetSingleSystemCountryCodeAsync(Code);
        }
        
        public void RemoveSystemCountryCode(System.Guid Code) {
            base.Channel.RemoveSystemCountryCode(Code);
        }
        
        public System.Threading.Tasks.Task RemoveSystemCountryCodeAsync(System.Guid Code) {
            return base.Channel.RemoveSystemCountryCodeAsync(Code);
        }
        
        public void UpdateSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] items) {
            base.Channel.UpdateSystemCountryCode(items);
        }
        
        public System.Threading.Tasks.Task UpdateSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] items) {
            return base.Channel.UpdateSystemCountryCodeAsync(items);
        }
        
        public void AddSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            base.Channel.AddSystemLanguageCode(item);
        }
        
        public System.Threading.Tasks.Task AddSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] item) {
            return base.Channel.AddSystemLanguageCodeAsync(item);
        }
        
        public CareerCloud.Pocos.SystemLanguageCodePoco[] GetAllSystemLanguageCode() {
            return base.Channel.GetAllSystemLanguageCode();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco[]> GetAllSystemLanguageCodeAsync() {
            return base.Channel.GetAllSystemLanguageCodeAsync();
        }
        
        public CareerCloud.Pocos.SystemLanguageCodePoco GetSingleSystemLanguageCode(System.Guid LanguageId) {
            return base.Channel.GetSingleSystemLanguageCode(LanguageId);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco> GetSingleSystemLanguageCodeAsync(System.Guid LanguageId) {
            return base.Channel.GetSingleSystemLanguageCodeAsync(LanguageId);
        }
        
        public void RemoveSystemLanguageCode(System.Guid LanguageId) {
            base.Channel.RemoveSystemLanguageCode(LanguageId);
        }
        
        public System.Threading.Tasks.Task RemoveSystemLanguageCodeAsync(System.Guid LanguageId) {
            return base.Channel.RemoveSystemLanguageCodeAsync(LanguageId);
        }
        
        public void UpdateSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] items) {
            base.Channel.UpdateSystemLanguageCode(items);
        }
        
        public System.Threading.Tasks.Task UpdateSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] items) {
            return base.Channel.UpdateSystemLanguageCodeAsync(items);
        }
    }
}
