//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.Company {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Company.ICompany")]
    public interface ICompany {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyDescriptionResponse")]
        void AddCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyDescriptionResponse")]
        System.Threading.Tasks.Task AddCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyDescriptionResponse")]
        CareerCloud.Pocos.CompanyDescriptionPoco[] GetAllCompanyDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco[]> GetAllCompanyDescriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyDescriptionResponse")]
        CareerCloud.Pocos.CompanyDescriptionPoco GetSingleCompanyDescription(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco> GetSingleCompanyDescriptionAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyDescriptionResponse")]
        void RemoveCompanyDescription(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyDescriptionResponse")]
        System.Threading.Tasks.Task RemoveCompanyDescriptionAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyDescriptionResponse")]
        void UpdateCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyDescriptionResponse")]
        System.Threading.Tasks.Task UpdateCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobDescriptionResponse")]
        void AddCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task AddCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobDescriptionResponse")]
        CareerCloud.Pocos.CompanyJobDescriptionPoco[] GetAllCompanyJobDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco[]> GetAllCompanyJobDescriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionResponse")]
        CareerCloud.Pocos.CompanyJobDescriptionPoco GetSingleCompanyJobDescription(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco> GetSingleCompanyJobDescriptionAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionResponse")]
        void RemoveCompanyJobDescription(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobDescriptionAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionResponse")]
        void UpdateCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobEducationResponse")]
        CareerCloud.Pocos.CompanyJobEducationPoco[] GetAllCompanyJobEducation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco[]> GetAllCompanyJobEducationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobEducationResponse")]
        CareerCloud.Pocos.CompanyJobEducationPoco GetSingleCompanyJobEducation(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco> GetSingleCompanyJobEducationAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobEducationResponse")]
        void RemoveCompanyJobEducation(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobEducationResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobEducationAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobEducationResponse")]
        void UpdateCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobEducationResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobResponse")]
        CareerCloud.Pocos.CompanyJobPoco[] GetAllCompanyJob();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco[]> GetAllCompanyJobAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobResponse")]
        CareerCloud.Pocos.CompanyJobPoco GetSingleCompanyJob(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco> GetSingleCompanyJobAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJob", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobResponse")]
        void RemoveCompanyJob(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJob", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJob", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobResponse")]
        void UpdateCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJob", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobSkillResponse")]
        CareerCloud.Pocos.CompanyJobSkillPoco[] GetAllCompanyJobSkill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco[]> GetAllCompanyJobSkillAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobSkillResponse")]
        CareerCloud.Pocos.CompanyJobSkillPoco GetSingleCompanyJobSkill(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco> GetSingleCompanyJobSkillAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobSkillResponse")]
        void RemoveCompanyJobSkill(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobSkillResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobSkillAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobSkillResponse")]
        void UpdateCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobSkillResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyLocationResponse")]
        CareerCloud.Pocos.CompanyLocationPoco[] GetAllCompanyLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyLocationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco[]> GetAllCompanyLocationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyLocationResponse")]
        CareerCloud.Pocos.CompanyLocationPoco GetSingleCompanyLocation(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyLocationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco> GetSingleCompanyLocationAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyLocation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyLocationResponse")]
        void RemoveCompanyLocation(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyLocation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyLocationResponse")]
        System.Threading.Tasks.Task RemoveCompanyLocationAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyLocation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyLocationResponse")]
        void UpdateCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyLocation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyLocationResponse")]
        System.Threading.Tasks.Task UpdateCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyProfileResponse")]
        CareerCloud.Pocos.CompanyProfilePoco[] GetAllCompanyProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco[]> GetAllCompanyProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyProfileResponse")]
        CareerCloud.Pocos.CompanyProfilePoco GetSingleCompanyProfile(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco> GetSingleCompanyProfileAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyProfile", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyProfileResponse")]
        void RemoveCompanyProfile(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyProfile", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyProfileResponse")]
        System.Threading.Tasks.Task RemoveCompanyProfileAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyProfile", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyProfileResponse")]
        void UpdateCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyProfile", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyProfileResponse")]
        System.Threading.Tasks.Task UpdateCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyChannel : CareerCloud.UnitTests.Assignment5.Company.ICompany, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.Company.ICompany>, CareerCloud.UnitTests.Assignment5.Company.ICompany {
        
        public CompanyClient() {
        }
        
        public CompanyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] item) {
            base.Channel.AddCompanyDescription(item);
        }
        
        public System.Threading.Tasks.Task AddCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] item) {
            return base.Channel.AddCompanyDescriptionAsync(item);
        }
        
        public CareerCloud.Pocos.CompanyDescriptionPoco[] GetAllCompanyDescription() {
            return base.Channel.GetAllCompanyDescription();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco[]> GetAllCompanyDescriptionAsync() {
            return base.Channel.GetAllCompanyDescriptionAsync();
        }
        
        public CareerCloud.Pocos.CompanyDescriptionPoco GetSingleCompanyDescription(System.Guid id) {
            return base.Channel.GetSingleCompanyDescription(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco> GetSingleCompanyDescriptionAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyDescriptionAsync(id);
        }
        
        public void RemoveCompanyDescription(System.Guid id) {
            base.Channel.RemoveCompanyDescription(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyDescriptionAsync(System.Guid id) {
            return base.Channel.RemoveCompanyDescriptionAsync(id);
        }
        
        public void UpdateCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            base.Channel.UpdateCompanyDescription(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] items) {
            return base.Channel.UpdateCompanyDescriptionAsync(items);
        }
        
        public void AddCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] item) {
            base.Channel.AddCompanyJobDescription(item);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] item) {
            return base.Channel.AddCompanyJobDescriptionAsync(item);
        }
        
        public CareerCloud.Pocos.CompanyJobDescriptionPoco[] GetAllCompanyJobDescription() {
            return base.Channel.GetAllCompanyJobDescription();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco[]> GetAllCompanyJobDescriptionAsync() {
            return base.Channel.GetAllCompanyJobDescriptionAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobDescriptionPoco GetSingleCompanyJobDescription(System.Guid id) {
            return base.Channel.GetSingleCompanyJobDescription(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco> GetSingleCompanyJobDescriptionAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyJobDescriptionAsync(id);
        }
        
        public void RemoveCompanyJobDescription(System.Guid id) {
            base.Channel.RemoveCompanyJobDescription(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobDescriptionAsync(System.Guid id) {
            return base.Channel.RemoveCompanyJobDescriptionAsync(id);
        }
        
        public void UpdateCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            base.Channel.UpdateCompanyJobDescription(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] items) {
            return base.Channel.UpdateCompanyJobDescriptionAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobEducationPoco[] GetAllCompanyJobEducation() {
            return base.Channel.GetAllCompanyJobEducation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco[]> GetAllCompanyJobEducationAsync() {
            return base.Channel.GetAllCompanyJobEducationAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobEducationPoco GetSingleCompanyJobEducation(System.Guid id) {
            return base.Channel.GetSingleCompanyJobEducation(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco> GetSingleCompanyJobEducationAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyJobEducationAsync(id);
        }
        
        public void RemoveCompanyJobEducation(System.Guid id) {
            base.Channel.RemoveCompanyJobEducation(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobEducationAsync(System.Guid id) {
            return base.Channel.RemoveCompanyJobEducationAsync(id);
        }
        
        public void UpdateCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            base.Channel.UpdateCompanyJobEducation(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] items) {
            return base.Channel.UpdateCompanyJobEducationAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobPoco[] GetAllCompanyJob() {
            return base.Channel.GetAllCompanyJob();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco[]> GetAllCompanyJobAsync() {
            return base.Channel.GetAllCompanyJobAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobPoco GetSingleCompanyJob(System.Guid id) {
            return base.Channel.GetSingleCompanyJob(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco> GetSingleCompanyJobAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyJobAsync(id);
        }
        
        public void RemoveCompanyJob(System.Guid id) {
            base.Channel.RemoveCompanyJob(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobAsync(System.Guid id) {
            return base.Channel.RemoveCompanyJobAsync(id);
        }
        
        public void UpdateCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] items) {
            base.Channel.UpdateCompanyJob(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] items) {
            return base.Channel.UpdateCompanyJobAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyJobSkillPoco[] GetAllCompanyJobSkill() {
            return base.Channel.GetAllCompanyJobSkill();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco[]> GetAllCompanyJobSkillAsync() {
            return base.Channel.GetAllCompanyJobSkillAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobSkillPoco GetSingleCompanyJobSkill(System.Guid id) {
            return base.Channel.GetSingleCompanyJobSkill(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco> GetSingleCompanyJobSkillAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyJobSkillAsync(id);
        }
        
        public void RemoveCompanyJobSkill(System.Guid id) {
            base.Channel.RemoveCompanyJobSkill(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobSkillAsync(System.Guid id) {
            return base.Channel.RemoveCompanyJobSkillAsync(id);
        }
        
        public void UpdateCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            base.Channel.UpdateCompanyJobSkill(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] items) {
            return base.Channel.UpdateCompanyJobSkillAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyLocationPoco[] GetAllCompanyLocation() {
            return base.Channel.GetAllCompanyLocation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco[]> GetAllCompanyLocationAsync() {
            return base.Channel.GetAllCompanyLocationAsync();
        }
        
        public CareerCloud.Pocos.CompanyLocationPoco GetSingleCompanyLocation(System.Guid id) {
            return base.Channel.GetSingleCompanyLocation(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco> GetSingleCompanyLocationAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyLocationAsync(id);
        }
        
        public void RemoveCompanyLocation(System.Guid id) {
            base.Channel.RemoveCompanyLocation(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyLocationAsync(System.Guid id) {
            return base.Channel.RemoveCompanyLocationAsync(id);
        }
        
        public void UpdateCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            base.Channel.UpdateCompanyLocation(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] items) {
            return base.Channel.UpdateCompanyLocationAsync(items);
        }
        
        public CareerCloud.Pocos.CompanyProfilePoco[] GetAllCompanyProfile() {
            return base.Channel.GetAllCompanyProfile();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco[]> GetAllCompanyProfileAsync() {
            return base.Channel.GetAllCompanyProfileAsync();
        }
        
        public CareerCloud.Pocos.CompanyProfilePoco GetSingleCompanyProfile(System.Guid id) {
            return base.Channel.GetSingleCompanyProfile(id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco> GetSingleCompanyProfileAsync(System.Guid id) {
            return base.Channel.GetSingleCompanyProfileAsync(id);
        }
        
        public void RemoveCompanyProfile(System.Guid id) {
            base.Channel.RemoveCompanyProfile(id);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyProfileAsync(System.Guid id) {
            return base.Channel.RemoveCompanyProfileAsync(id);
        }
        
        public void UpdateCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            base.Channel.UpdateCompanyProfile(items);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] items) {
            return base.Channel.UpdateCompanyProfileAsync(items);
        }
    }
}
